// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type ExchangeRate record {
    # ISO 4217 currency code
    string currencyCode;
    # units of this currency per 1 USD
    decimal rateToUsd;
    # date this rate was last refreshed
    string asOfDate;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type Currency record {
    # ISO 4217 currency code
    string code;
    # currency display name
    string name;
};

public type CurrencyList record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Currency[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};
